services:
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - FASTF1_CACHE=/backend/app/cache
    volumes:
      - ./backend/app:/backend/app
  db:
    image: postgres:14.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '5432:5432'
  redis:
    image: redis:latest
    ports: ['6379:6379']

