version: '3.8'
services:
  db:
    image: postgres:14.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ['5432:5432']
  python:
    build: ./services/python
    depends_on: ['db']
    ports: ['8000:8000']
  redis:
    image: redis:latest
    ports: ['6379:6379']

